{{- if .Values.certificate.create }}
{{- $fullName := include "backend-android-patterns.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "backend-android-patterns.labels" . | nindent 4 }}
spec:
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . | quote }}
    {{- end }}
  secretName: {{ include "backend-android-patterns.tlsSecretName" . }}
  issuerRef:
  {{- .Values.certificate.issuerRef | toYaml | trimSuffix "\n" | nindent 4 }}
{{- end }}
